version: "3"
services:
  php:
    image: ghcr.io/shooktea/php-dev/php-dev:8.2.0
    ports: [ '8080:80' ]
    volumes: [ './:/usr/share/nginx/html/backend' ]
  db:
    image: postgres:15.1-alpine
    ports: [ '5432:5432' ]
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db
